MONGO_URL = "mongodb://localhost:27017/"
MONGO_DATABASE = "music_quiz"
MONGO_USERS_COLLECTION = "users"
MONGO_AUDIOS_COLLECTION = "audios"
MONGO_ARTISTS_COLLECTION = "artists"

VERSION = "2023-10-23-02-00"
